### ISSUE TITLE
Delay when receiving SMS

### ISSUE THREAD

**Issue by jakkra** [smslib/smslib-v3#17]
I'm having trouble that it takes between 30-40 s after I send a SMS, until SMSLib  receives it. I'm using a Dlink DWR-157 modem with Service.getInstance().S.SERIAL_POLLING = true; to get it to use. When I use the software that comes with the USB modem, it receives SMS quick. So no problem with the GSM. 
Any ideas why, or what I can do? 

I have the same problem in the  ReadMessage example (https://github.com/smslib/smslib-v3/blob/master/src/java/examples/modem/ReadMessages.java).

**Comment by tdelenikas** [comment]
You can try and lower the value of CNMI_EMULATOR_INTERVAL in Settings.java - or modify it in real time.

The value is expressed in seconds, with a default value of 30 seconds (rings a bell?)

You can try and lower it - but keep an eye in your modem's operation, as a low value may cause more problems in reception or errors.

**Comment by jakkra** [comment]
Solved my problem, thank you.
